### ISSUE TITLE
3Questions: k, training_set, weights

### ISSUE THREAD

**Issue by XueZ-phd** [FrederikWarburg/Burst-Image-Deblurring#3]
Dear FrederikWarburg:
Thanks for your great code!
But 3 questions make me confused for several days, I do need your generous help:

**1. About value k:** the value k is _not defined_ in line 78 of 'class UNet(nn.Module)', specifically in model.py, so, how should I set the k value?

**2. About training_set:** I have downloaded the ImageNet 2012 dataset for training. As we know, there are 1,000 subfolders in folder "ILSVRC2012_img_train", so, should I unzip the 1,000 subfolders to 1 same "train" folder instead of 1,000 folders?

**3. About weights:** May you please release your weights? 

Eagerly waiting for your response, Xue Zhang!

**Comment by FrederikWarburg** [comment]
Hi, 
Glad you find the code useful!

1. I experimented with a the top-k pooling, however couldn't get it to work probably, so I deleted it (at least I thought so) before making the repo public. Normal max-pooling is just top-1 pooling, so you can either delete k or set k=1. I will update the repo with this change, when I have more time.

2. Yes, I had all the images in the same folder. Such that you get a list of all you images with line https://github.com/FrederikWarburg/Burst-Image-Deblurring/blob/1359093179ebca9c1d53fb55590e70bc35844f8d/tools.py#L141 

3. I don't have the weights. Sorry about this. But since this repo have gained so much attention, I will definitely upload the weights soon (probably in the start of February, as I'm busy with my thesis and a paper this month).

Good luck with the code. Let me know if you have other quick questions :)

**Comment by XueZ-phd** [comment]
Dear  FrederikWarburg:
Thanks for your reply!  
But I think there may be another bug in your code:
 https://github.com/FrederikWarburg/Burst-Image-Deblurring/blob/1359093179ebca9c1d53fb55590e70bc35844f8d/model.py#L96-L99.
After setting those “in_channels” to (96) 384+384+384,  (97) 256+256+256, (98) 192+192+128, (99) 96+96+64, the code works for testing.
Good luck tou you!


发件人: Frederik Warburg
发送时间: 2020年1月13日 16:40
收件人: FrederikWarburg/Burst-Image-Deblurring
抄送: XueZ-phd; Author
主题: Re: [FrederikWarburg/Burst-Image-Deblurring] 3Questions: k,training_set, weights (#3)

Hi,
Glad you find the code useful!
1. I experimented with a the top-k pooling, however couldn't get it to work probably, so I deleted it (at least I thought so) before making the repo public. Normal max-pooling is just top-1 pooling, so you can either delete k or set k=1. I will update the repo with this change, when I have more time.
2. Yes, I had all the images in the same folder. Such that you get a list of all you images with line https://github.com/FrederikWarburg/Burst-Image-Deblurring/blob/1359093179ebca9c1d53fb55590e70bc35844f8d/tools.py#L141
3. I don't have the weights. Sorry about this. But since this repo have gained so much attention, I will definitely upload the weights soon (probably in the start of February, as I'm busy with my thesis and a paper this month).
Good luck with the code. Let me know if you have other quick questions :)
